# Generated by Django 5.2.8 on 2025-11-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL (заповниться автоматично, якщо порожній)', max_length=255, unique=True),
        ),
    ]
