"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()  # load environment

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a(if&9uic12gr_r@ksdij+hqf=%)**e^^xu@5u4)aq@!&xwi0d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# core/settings.py
ALLOWED_HOSTS = ['beddingshop.shop', 'www.beddingshop.shop', '173.242.51.228']  # Додайте внутрішні IP вашого ПК# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',  # <-- Додайте цей рядок

    # Наші додатки
    'users',
    'store',
    'cart',
    'orders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], 'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # --- ДОДАЙТЕ ЦЕЙ РЯДОК ---
                'cart.context_processors.cart',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'bedding_shop_db',  # Назва бази, яку ви створили
        'USER': 'bedding_user',  # Ваш логін (зазвичай root)
        'PASSWORD': 'Soroka292004@',  # Ваш пароль (у XAMPP часто порожній)
        'HOST': '127.0.0.1',  # Локальний хост
        'PORT': '3306',  # Стандартний порт
        'OPTIONS': {
            # Важливо для строгого режиму SQL
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User'

# URL-адреса, за якою браузер буде шукати медіа-файли

# Абсолютний шлях до папки, де Django буде зберігати завантажені файли.
# os.path.join(BASE_DIR, 'media') - створює папку 'media' в корені проєкту.
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# --- Налаштування статичних файлів (CSS, JS) ---
# (Ми їх ще не використовували, але одразу налаштуємо)

# URL-адреса для статичних файлів
STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Папка, де Django буде шукати наші власні CSS/JS файли
#STATICFILES_DIRS = [
#    os.path.join(BASE_DIR, 'static'),
#]

CART_SESSION_ID = 'cart'

# Куди перенаправляти після успішного входу
LOGIN_REDIRECT_URL = '/'  # На головну

# URL сторінки входу (якщо неавторизований юзер лізе в профіль)
LOGIN_URL = '/users/login/'

# core/settings.py

# --- НАЛАШТУВАННЯ ТЕЛЕГРАМ ---
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN')
TELEGRAM_MANAGER_CHAT_ID = os.getenv('TELEGRAM_MANAGER_CHAT_ID')
TELEGRAM_CHANEL_BOT = '8558954683:AAHdf75VRDgyb807502XBA79J51lnKlnaBw'
TELEGRAM_CHANNEL_ID = '-1003603057560'  # 👈 Мінус має бути всередині лапок!# -----------------------------
