# Generated by Django 5.2.8 on 2025-11-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефону')),
                ('delivery_method', models.CharField(choices=[('nova_poshta', 'Нова Пошта'), ('ukr_poshta', 'Укрпошта')], default='nova_poshta', max_length=20, verbose_name='Спосіб доставки')),
                ('city', models.CharField(default='', max_length=100, verbose_name='Місто / Населений пункт')),
                ('warehouse', models.CharField(default='', max_length=100, verbose_name='Відділення / Поштомат')),
                ('payment_method', models.CharField(choices=[('cod', 'Накладений платіж (Оплата при отриманні)'), ('card', 'Оплата карткою')], default='cod', max_length=20, verbose_name='Спосіб оплати')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментар до замовлення')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('status', models.CharField(choices=[('new', 'Нове'), ('processing', 'В обробці'), ('shipped', 'Відправлено'), ('completed', 'Виконано'), ('canceled', 'Скасовано')], default='new', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна на момент покупки')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
            ],
            options={
                'verbose_name': 'Товар у замовленні',
                'verbose_name_plural': 'Товари у замовленні',
            },
        ),
    ]
